COMPONENT=ApplicationC
CFLAGS += -DMTS300CB
SENSORBOARD=mts300
CFLAGS += -I$(SZTETOSDIR)/lib/StreamStorage
CFLAGS += -I$(SZTETOSDIR)/lib/StorageFrame
CFLAGS += -I$(SZTETOSDIR)/lib/Dfrf
CFLAGS += -I$(SZTETOSDIR)/lib/StreamUploaderDfrf

include $(MAKERULES)