COMPONENT=SSTest_MTS400_App
CFLAGS += -I$(TOSDIR)/chips/sht11
CFLAGS += -I$(SZTETOSDIR)/lib/Mts400
CFLAGS += -I$(SZTETOSDIR)/lib/FastSerial
CFLAGS += -I$(SZTETOSDIR)/lib/StreamStorage
CFLAGS += -I$(SZTETOSDIR)/lib/StorageFrame
CFLAGS += -I$(SZTETOSDIR)/lib/StreamUploader
include $(MAKERULES)