/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ctrlMsg'
 * message type.
 */

public class ctrlMsgTS extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 12;

    /** The Active Message type associated with this message. */
    public static final int am_type = 10;

    /** Create a new ctrlMsg of size 8. */
    public ctrlMsgTS(byte am_type) {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(am_type);
    }

    /** Create a new ctrlMsg of the given data_length. */
    public ctrlMsgTS(int data_length, byte am_type) {
        super(data_length);
        amTypeSet(am_type);
    }

    /**
     * Create a new ctrlMsg with the given data_length
     * and base offset.
     */
    public ctrlMsgTS(int data_length, int base_offset, byte am_type) {
        super(data_length, base_offset);
        amTypeSet(am_type);
    }

    /**
     * Create a new ctrlMsg using the given byte array
     * as backing store.
     */
    public ctrlMsgTS(byte[] data, byte am_type) {
        super(data);
        amTypeSet(am_type);
    }

    /**
     * Create a new ctrlMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ctrlMsgTS(byte[] data, int base_offset, byte am_type) {
        super(data, base_offset);
        amTypeSet(am_type);
    }

    /**
     * Create a new ctrlMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ctrlMsgTS(byte[] data, int base_offset, int data_length, byte am_type) {
        super(data, base_offset, data_length);
        amTypeSet(am_type);
    }

    /**
     * Create a new ctrlMsg embedded in the given message
     * at the given base offset.
     */
    public ctrlMsgTS(net.tinyos.message.Message msg, int base_offset, byte am_type) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(am_type);
    }

    /**
     * Create a new ctrlMsg embedded in the given message
     * at the given base offset and length.
     */
    public ctrlMsgTS(net.tinyos.message.Message msg, int base_offset, int data_length, byte am_type) {
        super(msg, base_offset, data_length);
        amTypeSet(am_type);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ctrlMsg> \n";
      try {
        s += "  [min_address=0x"+Long.toHexString(get_min_address())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [max_address=0x"+Long.toHexString(get_max_address())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: min_address
    //   Field type: long, unsigned
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'min_address' is signed (false).
     */
    public static boolean isSigned_min_address() {
        return false;
    }

    /**
     * Return whether the field 'min_address' is an array (false).
     */
    public static boolean isArray_min_address() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'min_address'
     */
    public static int offset_min_address() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'min_address'
     */
    public static int offsetBits_min_address() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'min_address'
     */
    public long get_min_address() {
        return (long)getUIntBEElement(offsetBits_min_address(), 32);
    }

    /**
     * Set the value of the field 'min_address'
     */
    public void set_min_address(long value) {
        setUIntBEElement(offsetBits_min_address(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'min_address'
     */
    public static int size_min_address() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'min_address'
     */
    public static int sizeBits_min_address() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: max_address
    //   Field type: long, unsigned
    //   Offset (bits): 32
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'max_address' is signed (false).
     */
    public static boolean isSigned_max_address() {
        return false;
    }

    /**
     * Return whether the field 'max_address' is an array (false).
     */
    public static boolean isArray_max_address() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'max_address'
     */
    public static int offset_max_address() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'max_address'
     */
    public static int offsetBits_max_address() {
        return 32;
    }

    /**
     * Return the value (as a long) of the field 'max_address'
     */
    public long get_max_address() {
        return (long)getUIntBEElement(offsetBits_max_address(), 32);
    }

    /**
     * Set the value of the field 'max_address'
     */
    public void set_max_address(long value) {
        setUIntBEElement(offsetBits_max_address(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'max_address'
     */
    public static int size_max_address() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'max_address'
     */
    public static int sizeBits_max_address() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for timestamp
    //   Field type: long, unsigned
    //   Offset (bits): 64
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

   /**
     * Return the offset (in bytes) of the field 'max_address'
     */
    public static int offset_timestamp() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'max_address'
     */
    public static int offsetBits_timestamp() {
        return 64;
    }

    /**
     * Return the value (as a long) of the field 'max_address'
     */
    public Long get_timestamp() {
    	//System.out.println(Long.toHexString((Long)getUIntBEElement(offsetBits_timestamp(), 32)));
    	//System.out.println(Long.toHexString(-1*(0xffffffffL<<32|(Long)getUIntBEElement(offsetBits_timestamp(), 32))));
        //return -1*(0xffffffffL<<32|(Long)getUIntBEElement(offsetBits_timestamp(), 32));
    	return (Long)getUIntBEElement(offsetBits_timestamp(), 32);
    }

    /**
     * Set the value of the field 'max_address'
     */
    public void set_timestamp(long value) {
        setUIntBEElement(offsetBits_max_address(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'max_address'
     */
    public static int size_timestamp() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'max_address'
     */
    public static int sizeBits_timestamp() {
        return 32;
    }
    
}
