/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'helloMsg'
 * message type.
 */

public class helloMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */

    /** Create a new helloMsg of size 2. */
    public helloMsg(byte am_type) {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(am_type);
    }

    /** Create a new helloMsg of the given data_length. */
    public helloMsg(int data_length,byte am_type) {
        super(data_length);
        amTypeSet(am_type);
    }

    /**
     * Create a new helloMsg with the given data_length
     * and base offset.
     */
    public helloMsg(int data_length, int base_offset,byte am_type) {
        super(data_length, base_offset);
        amTypeSet(am_type);
    }

    /**
     * Create a new helloMsg using the given byte array
     * as backing store.
     */
    public helloMsg(byte[] data,byte am_type) {
        super(data);
        amTypeSet(am_type);
    }

    /**
     * Create a new helloMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public helloMsg(byte[] data, int base_offset,byte am_type) {
        super(data, base_offset);
        amTypeSet(am_type);
    }

    /**
     * Create a new helloMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public helloMsg(byte[] data, int base_offset, int data_length,byte am_type) {
        super(data, base_offset, data_length);
        amTypeSet(am_type);
    }

    /**
     * Create a new helloMsg embedded in the given message
     * at the given base offset.
     */
    public helloMsg(net.tinyos.message.Message msg, int base_offset,byte am_type) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(am_type);
    }

    /**
     * Create a new helloMsg embedded in the given message
     * at the given base offset and length.
     */
    public helloMsg(net.tinyos.message.Message msg, int base_offset, int data_length,byte am_type) {
        super(msg, base_offset, data_length);
        amTypeSet(am_type);
    }


	/**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <helloMsg> \n";
      try {
        s += "  [nodeid=0x"+Long.toHexString(get_nodeid())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeid
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeid' is signed (false).
     */
    public static boolean isSigned_nodeid() {
        return false;
    }

    /**
     * Return whether the field 'nodeid' is an array (false).
     */
    public static boolean isArray_nodeid() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeid'
     */
    public static int offset_nodeid() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeid'
     */
    public static int offsetBits_nodeid() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'nodeid'
     */
    public int get_nodeid() {
        return (int)getUIntBEElement(offsetBits_nodeid(), 16);
    }

    /**
     * Set the value of the field 'nodeid'
     */
    public void set_nodeid(int value) {
        setUIntBEElement(offsetBits_nodeid(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeid'
     */
    public static int size_nodeid() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeid'
     */
    public static int sizeBits_nodeid() {
        return 16;
    }

}
