JOBDIR=javasrc/benchmark/common
JPKGPREFIX=benchmark.common
BUILD_EXTRA_DEPS += $(JOBDIR)/CtrlMsgT.java $(JOBDIR)/DataMsgT.java $(JOBDIR)/SyncMsgT.java
BUILD_EXTRA_DEPS += $(JOBDIR)/SetupMsgT.java $(JOBDIR)/StatT.java $(JOBDIR)/ProfileT.java $(JOBDIR)/SetupT.java
CLEAN_EXTRA      += main.elf $(JOBDIR)/*.class $(JOBDIR)/*T.java

$(JOBDIR)/StatT.java: BenchmarkCore.h Makefile
	mig -target=$(PLATFORM) $(CFLAGS) -java-classname=$(JPKGPREFIX).StatT java BenchmarkCore.h stat_t -o $@
	
$(JOBDIR)/ProfileT.java: BenchmarkCore.h
	mig -target=$(PLATFORM) $(CFLAGS) -java-classname=$(JPKGPREFIX).ProfileT java BenchmarkCore.h profile_t -o $@

$(JOBDIR)/SetupT.java: BenchmarkCore.h
	mig -target=$(PLATFORM) -java-classname=$(JPKGPREFIX).SetupT java BenchmarkCore.h setup_t -o $@

$(JOBDIR)/CtrlMsgT.java: Messages.h
	mig -target=$(PLATFORM) -java-classname=$(JPKGPREFIX).CtrlMsgT java Messages.h ctrlmsg_t -o $@
	
$(JOBDIR)/SyncMsgT.java: Messages.h
	mig -target=$(PLATFORM) -java-classname=$(JPKGPREFIX).SyncMsgT java Messages.h syncmsg_t -o $@

$(JOBDIR)/SetupMsgT.java: Messages.h
	mig -target=$(PLATFORM) -java-classname=$(JPKGPREFIX).SetupMsgT java Messages.h setupmsg_t -o $@
	
$(JOBDIR)/DataMsgT.java: Messages.h
	mig -target=$(PLATFORM) -java-classname=$(JPKGPREFIX).DataMsgT java Messages.h datamsg_t -o $@
	
BUILD_EXTRA_DEPS += $(JOBDIR)/BenchmarkStatic.java
CLEAN_EXTRA      += $(JOBDIR)/BenchmarkStatic.java

$(JOBDIR)/BenchmarkStatic.java: BenchmarkCore.h Messages.h
	ncg -target=$(PLATFORM) -o $@ -java-classname=$(JPKGPREFIX).BenchmarkStatic java Messages.h \
	MAX_TIMER_COUNT SETUP_BASE CTRL_SETUP_SYN SYNC_SETUP_ACK CTRL_START CTRL_RESET \
	CTRL_STAT_REQ DATA_STAT_OK CTRL_PROFILE_REQ DATA_PROFILE_OK \
	GLOBAL_USE_ACK GLOBAL_USE_BCAST GLOBAL_USE_MAC_LPL GLOBAL_USE_MAC_PLINK \
	LPL_WAKEUP_OFFSET PLINK_RETRIES_OFFSET PLINK_DELAY_OFFSET MAC_SETUP_LENGTH
