/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../GreenHouse.h.
 */

public class Constants  {
    public static final byte NREADINGS = 2;
    public static final short DEFAULT_INTERVAL = 1000;
}
