/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'CtrlMsg'
 * message type.
 */

public class CtrlMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 3;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 2;

    /** Create a new CtrlMsg of size 3. */
    public CtrlMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new CtrlMsg of the given data_length. */
    public CtrlMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CtrlMsg with the given data_length
     * and base offset.
     */
    public CtrlMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CtrlMsg using the given byte array
     * as backing store.
     */
    public CtrlMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CtrlMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public CtrlMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CtrlMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public CtrlMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CtrlMsg embedded in the given message
     * at the given base offset.
     */
    public CtrlMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CtrlMsg embedded in the given message
     * at the given base offset and length.
     */
    public CtrlMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <CtrlMsg> \n";
      try {
        s += "  [instr=0x"+Long.toHexString(get_instr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [micPeriod=0x"+Long.toHexString(get_micPeriod())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: instr
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'instr' is signed (false).
     */
    public static boolean isSigned_instr() {
        return false;
    }

    /**
     * Return whether the field 'instr' is an array (false).
     */
    public static boolean isArray_instr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'instr'
     */
    public static int offset_instr() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'instr'
     */
    public static int offsetBits_instr() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'instr'
     */
    public short get_instr() {
        return (short)getUIntBEElement(offsetBits_instr(), 8);
    }

    /**
     * Set the value of the field 'instr'
     */
    public void set_instr(short value) {
        setUIntBEElement(offsetBits_instr(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'instr'
     */
    public static int size_instr() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'instr'
     */
    public static int sizeBits_instr() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: micPeriod
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'micPeriod' is signed (false).
     */
    public static boolean isSigned_micPeriod() {
        return false;
    }

    /**
     * Return whether the field 'micPeriod' is an array (false).
     */
    public static boolean isArray_micPeriod() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'micPeriod'
     */
    public static int offset_micPeriod() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'micPeriod'
     */
    public static int offsetBits_micPeriod() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'micPeriod'
     */
    public int get_micPeriod() {
        return (int)getUIntBEElement(offsetBits_micPeriod(), 16);
    }

    /**
     * Set the value of the field 'micPeriod'
     */
    public void set_micPeriod(int value) {
        setUIntBEElement(offsetBits_micPeriod(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'micPeriod'
     */
    public static int size_micPeriod() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'micPeriod'
     */
    public static int sizeBits_micPeriod() {
        return 16;
    }

}
