/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'MicMsg'
 * message type.
 */

public class MicMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 114;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new MicMsg of size 114. */
    public MicMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new MicMsg of the given data_length. */
    public MicMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg with the given data_length
     * and base offset.
     */
    public MicMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg using the given byte array
     * as backing store.
     */
    public MicMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public MicMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public MicMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg embedded in the given message
     * at the given base offset.
     */
    public MicMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg embedded in the given message
     * at the given base offset and length.
     */
    public MicMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <MicMsg> \n";
      try {
        s += "  [data=";
        for (int i = 0; i < 110; i++) {
          s += "0x"+Long.toHexString(getElement_data(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [bufferNum=0x"+Long.toHexString(get_bufferNum())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [gainVal=0x"+Long.toHexString(get_gainVal())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data
    //   Field type: short[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data' is signed (false).
     */
    public static boolean isSigned_data() {
        return false;
    }

    /**
     * Return whether the field 'data' is an array (true).
     */
    public static boolean isArray_data() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data'
     */
    public static int offset_data(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 110) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data'
     */
    public static int offsetBits_data(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 110) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'data' as a short[]
     */
    public short[] get_data() {
        short[] tmp = new short[110];
        for (int index0 = 0; index0 < numElements_data(0); index0++) {
            tmp[index0] = getElement_data(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data' from the given short[]
     */
    public void set_data(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'data'
     */
    public short getElement_data(int index1) {
        return (short)getUIntBEElement(offsetBits_data(index1), 8);
    }

    /**
     * Set an element of the array 'data'
     */
    public void setElement_data(int index1, short value) {
        setUIntBEElement(offsetBits_data(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data'
     */
    public static int totalSize_data() {
        return (880 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data'
     */
    public static int totalSizeBits_data() {
        return 880;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data'
     */
    public static int elementSize_data() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data'
     */
    public static int elementSizeBits_data() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'data'
     */
    public static int numDimensions_data() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data'
     */
    public static int numElements_data() {
        return 110;
    }

    /**
     * Return the number of elements in the array 'data'
     * for the given dimension.
     */
    public static int numElements_data(int dimension) {
      int array_dims[] = { 110,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'data' with a String
     */
    public void setString_data(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_data(i, (short)s.charAt(i));
         }
         setElement_data(i, (short)0); //null terminate
    }

    /**
     * Read the array 'data' as a String
     */
    public String getString_data() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,110)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_data(i) == (char)0) break;
             carr[i] = (char)getElement_data(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: bufferNum
    //   Field type: int, unsigned
    //   Offset (bits): 880
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'bufferNum' is signed (false).
     */
    public static boolean isSigned_bufferNum() {
        return false;
    }

    /**
     * Return whether the field 'bufferNum' is an array (false).
     */
    public static boolean isArray_bufferNum() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'bufferNum'
     */
    public static int offset_bufferNum() {
        return (880 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'bufferNum'
     */
    public static int offsetBits_bufferNum() {
        return 880;
    }

    /**
     * Return the value (as a int) of the field 'bufferNum'
     */
    public int get_bufferNum() {
        return (int)getUIntBEElement(offsetBits_bufferNum(), 16);
    }

    /**
     * Set the value of the field 'bufferNum'
     */
    public void set_bufferNum(int value) {
        setUIntBEElement(offsetBits_bufferNum(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'bufferNum'
     */
    public static int size_bufferNum() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'bufferNum'
     */
    public static int sizeBits_bufferNum() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: gainVal
    //   Field type: int, unsigned
    //   Offset (bits): 896
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'gainVal' is signed (false).
     */
    public static boolean isSigned_gainVal() {
        return false;
    }

    /**
     * Return whether the field 'gainVal' is an array (false).
     */
    public static boolean isArray_gainVal() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'gainVal'
     */
    public static int offset_gainVal() {
        return (896 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'gainVal'
     */
    public static int offsetBits_gainVal() {
        return 896;
    }

    /**
     * Return the value (as a int) of the field 'gainVal'
     */
    public int get_gainVal() {
        return (int)getUIntBEElement(offsetBits_gainVal(), 16);
    }

    /**
     * Set the value of the field 'gainVal'
     */
    public void set_gainVal(int value) {
        setUIntBEElement(offsetBits_gainVal(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'gainVal'
     */
    public static int size_gainVal() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'gainVal'
     */
    public static int sizeBits_gainVal() {
        return 16;
    }

}
