/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'MicMsg'
 * message type.
 */

public class MicMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 20;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new MicMsg of size 20. */
    public MicMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new MicMsg of the given data_length. */
    public MicMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg with the given data_length
     * and base offset.
     */
    public MicMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg using the given byte array
     * as backing store.
     */
    public MicMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public MicMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public MicMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg embedded in the given message
     * at the given base offset.
     */
    public MicMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MicMsg embedded in the given message
     * at the given base offset and length.
     */
    public MicMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <MicMsg> \n";
      try {
        s += "  [micData=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_micData(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: micData
    //   Field type: int[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'micData' is signed (false).
     */
    public static boolean isSigned_micData() {
        return false;
    }

    /**
     * Return whether the field 'micData' is an array (true).
     */
    public static boolean isArray_micData() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'micData'
     */
    public static int offset_micData(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'micData'
     */
    public static int offsetBits_micData(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'micData' as a int[]
     */
    public int[] get_micData() {
        int[] tmp = new int[10];
        for (int index0 = 0; index0 < numElements_micData(0); index0++) {
            tmp[index0] = getElement_micData(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'micData' from the given int[]
     */
    public void set_micData(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_micData(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'micData'
     */
    public int getElement_micData(int index1) {
        return (int)getUIntBEElement(offsetBits_micData(index1), 16);
    }

    /**
     * Set an element of the array 'micData'
     */
    public void setElement_micData(int index1, int value) {
        setUIntBEElement(offsetBits_micData(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'micData'
     */
    public static int totalSize_micData() {
        return (160 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'micData'
     */
    public static int totalSizeBits_micData() {
        return 160;
    }

    /**
     * Return the size, in bytes, of each element of the array 'micData'
     */
    public static int elementSize_micData() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'micData'
     */
    public static int elementSizeBits_micData() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'micData'
     */
    public static int numDimensions_micData() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'micData'
     */
    public static int numElements_micData() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'micData'
     * for the given dimension.
     */
    public static int numElements_micData(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
