/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ReadyMsg'
 * message type.
 */

public class ReadyMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 6;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 3;

    /** Create a new ReadyMsg of size 6. */
    public ReadyMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ReadyMsg of the given data_length. */
    public ReadyMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadyMsg with the given data_length
     * and base offset.
     */
    public ReadyMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadyMsg using the given byte array
     * as backing store.
     */
    public ReadyMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadyMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ReadyMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadyMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ReadyMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadyMsg embedded in the given message
     * at the given base offset.
     */
    public ReadyMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadyMsg embedded in the given message
     * at the given base offset and length.
     */
    public ReadyMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ReadyMsg> \n";
      try {
        s += "  [usActualPeriod=0x"+Long.toHexString(get_usActualPeriod())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sampleNum=0x"+Long.toHexString(get_sampleNum())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: usActualPeriod
    //   Field type: long, unsigned
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'usActualPeriod' is signed (false).
     */
    public static boolean isSigned_usActualPeriod() {
        return false;
    }

    /**
     * Return whether the field 'usActualPeriod' is an array (false).
     */
    public static boolean isArray_usActualPeriod() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'usActualPeriod'
     */
    public static int offset_usActualPeriod() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'usActualPeriod'
     */
    public static int offsetBits_usActualPeriod() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'usActualPeriod'
     */
    public long get_usActualPeriod() {
        return (long)getUIntBEElement(offsetBits_usActualPeriod(), 32);
    }

    /**
     * Set the value of the field 'usActualPeriod'
     */
    public void set_usActualPeriod(long value) {
        setUIntBEElement(offsetBits_usActualPeriod(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'usActualPeriod'
     */
    public static int size_usActualPeriod() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'usActualPeriod'
     */
    public static int sizeBits_usActualPeriod() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sampleNum
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sampleNum' is signed (false).
     */
    public static boolean isSigned_sampleNum() {
        return false;
    }

    /**
     * Return whether the field 'sampleNum' is an array (false).
     */
    public static boolean isArray_sampleNum() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sampleNum'
     */
    public static int offset_sampleNum() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sampleNum'
     */
    public static int offsetBits_sampleNum() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'sampleNum'
     */
    public int get_sampleNum() {
        return (int)getUIntBEElement(offsetBits_sampleNum(), 16);
    }

    /**
     * Set the value of the field 'sampleNum'
     */
    public void set_sampleNum(int value) {
        setUIntBEElement(offsetBits_sampleNum(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sampleNum'
     */
    public static int size_sampleNum() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sampleNum'
     */
    public static int sizeBits_sampleNum() {
        return 16;
    }

}
