#!/usr/bin/python
import sys
if sys.platform.startswith("cygwin"):
  from getdevicescygwin import getAllDevices
elif sys.platform.startswith("linux"):
  from getdeviceslinux import getAllDevices
else:
  print("Unknown platform: "+sys.platform)
  sys.exit(0)
devices=getAllDevices()
if len(devices)==0:
  print("No devices found.")
else:
  print("Loc".rjust(4)+" "+\
      "VID".rjust(4)+" "+\
      "PID".rjust(4)+" "+\
      "Serial".rjust(10)+" "+\
      "Device".rjust(15)+" "+\
      "Active".rjust(6)+" "+\
      "Manufacturer; Description")
  for device in devices:
    print(device['location'].rjust(4)+" "+\
      device['vid'].rjust(4)+" "+\
      device['pid'].rjust(4)+" "+\
      device['serialnum'].rjust(10)+" "+\
      device['port'].rjust(15)+" "+\
      str(device['active']).rjust(6)+" "+\
      device['manufacturer']+"; "+device['description'])