#!/usr/bin/python
import sys
if sys.platform.startswith("cygwin"):
  from getdevicescygwin import getAllDevices
elif sys.platform.startswith("linux"):
  from getdeviceslinux import getAllDevices
else:
  print("Unknown platform: "+sys.platform)
  sys.exit(0)
devices=getAllDevices()
if len(devices)==0:
  print("No devices found.")
else:
  print("Loc\tVID\tPID\tSerial\tDevice\tActive\tDescription")
  x=0
  for device in devices:
    print(device['location']+"\t"+device['vid']+"\t"+device['pid']+"\t"+device['serialnum']+"\t"\
      +device['port']+"\t"+str(device['active'])+"\t"+device['manufacturer']+","+device['description'])
    print('{0:2d} {1:3d} {2:4d}'.format(x, x*x, x*x*x))
    x+=200