COMPONENT=ApplicationC
CFLAGS += -I$(SZTETOSDIR)/sensorboards/Mts300
CFLAGS += -I$(SZTETOSDIR)/lib/Atm128FastAdc
CFLAGS += -I$(SZTETOSDIR)/lib/StreamStorage
CFLAGS += -I$(SZTETOSDIR)/lib/StorageFrame
CFLAGS += -I$(SZTETOSDIR)/lib/StreamUploader
CFLAGS += -I..
SENSORBOARD=mts300
CFLAGS += -DMTS300CB
include $(MAKERULES)