#ifndef NETWORK_H
#define NETWORK_H
enum{
	FLAG_DATA=1,
	BEACON_INTERVAL=1000,
	INIT_DISCOVERY=10*BEACON_INTERVAL,
	MAX_NEIGHBOR=1,
	MAX_BS_NODEID=10,
	LOST_LIMIT=0xff-5,
	WAKE_TIME=5,
};
#endif /* NETWORK_H */
