/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ctrlMsg'
 * message type.
 */

public class ctrlMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 10;

    /** Create a new ctrlMsg of size 4. */
    public ctrlMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ctrlMsg of the given data_length. */
    public ctrlMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ctrlMsg with the given data_length
     * and base offset.
     */
    public ctrlMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ctrlMsg using the given byte array
     * as backing store.
     */
    public ctrlMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ctrlMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ctrlMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ctrlMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ctrlMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ctrlMsg embedded in the given message
     * at the given base offset.
     */
    public ctrlMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ctrlMsg embedded in the given message
     * at the given base offset and length.
     */
    public ctrlMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ctrlMsg> \n";
      try {
        s += "  [startpage=0x"+Long.toHexString(get_startpage())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [endpage=0x"+Long.toHexString(get_endpage())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: startpage
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'startpage' is signed (false).
     */
    public static boolean isSigned_startpage() {
        return false;
    }

    /**
     * Return whether the field 'startpage' is an array (false).
     */
    public static boolean isArray_startpage() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'startpage'
     */
    public static int offset_startpage() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'startpage'
     */
    public static int offsetBits_startpage() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'startpage'
     */
    public int get_startpage() {
        return (int)getUIntElement(offsetBits_startpage(), 16);
    }

    /**
     * Set the value of the field 'startpage'
     */
    public void set_startpage(int value) {
        setUIntElement(offsetBits_startpage(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'startpage'
     */
    public static int size_startpage() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'startpage'
     */
    public static int sizeBits_startpage() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: endpage
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'endpage' is signed (false).
     */
    public static boolean isSigned_endpage() {
        return false;
    }

    /**
     * Return whether the field 'endpage' is an array (false).
     */
    public static boolean isArray_endpage() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'endpage'
     */
    public static int offset_endpage() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'endpage'
     */
    public static int offsetBits_endpage() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'endpage'
     */
    public int get_endpage() {
        return (int)getUIntElement(offsetBits_endpage(), 16);
    }

    /**
     * Set the value of the field 'endpage'
     */
    public void set_endpage(int value) {
        setUIntElement(offsetBits_endpage(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'endpage'
     */
    public static int size_endpage() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'endpage'
     */
    public static int sizeBits_endpage() {
        return 16;
    }

}
