/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ControlMsg'
 * message type.
 */

public class ControlMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new ControlMsg of size 2. */
    public ControlMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ControlMsg of the given data_length. */
    public ControlMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ControlMsg with the given data_length
     * and base offset.
     */
    public ControlMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ControlMsg using the given byte array
     * as backing store.
     */
    public ControlMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ControlMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ControlMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ControlMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ControlMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ControlMsg embedded in the given message
     * at the given base offset.
     */
    public ControlMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ControlMsg embedded in the given message
     * at the given base offset and length.
     */
    public ControlMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ControlMsg> \n";
      try {
        s += "  [nodeID=0x"+Long.toHexString(get_nodeID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [instr=0x"+Long.toHexString(get_instr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeID
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeID' is signed (false).
     */
    public static boolean isSigned_nodeID() {
        return false;
    }

    /**
     * Return whether the field 'nodeID' is an array (false).
     */
    public static boolean isArray_nodeID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeID'
     */
    public static int offset_nodeID() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeID'
     */
    public static int offsetBits_nodeID() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'nodeID'
     */
    public short get_nodeID() {
        return (short)getUIntBEElement(offsetBits_nodeID(), 8);
    }

    /**
     * Set the value of the field 'nodeID'
     */
    public void set_nodeID(short value) {
        setUIntBEElement(offsetBits_nodeID(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeID'
     */
    public static int size_nodeID() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeID'
     */
    public static int sizeBits_nodeID() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: instr
    //   Field type: short, unsigned
    //   Offset (bits): 8
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'instr' is signed (false).
     */
    public static boolean isSigned_instr() {
        return false;
    }

    /**
     * Return whether the field 'instr' is an array (false).
     */
    public static boolean isArray_instr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'instr'
     */
    public static int offset_instr() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'instr'
     */
    public static int offsetBits_instr() {
        return 8;
    }

    /**
     * Return the value (as a short) of the field 'instr'
     */
    public short get_instr() {
        return (short)getUIntBEElement(offsetBits_instr(), 8);
    }

    /**
     * Set the value of the field 'instr'
     */
    public void set_instr(short value) {
        setUIntBEElement(offsetBits_instr(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'instr'
     */
    public static int size_instr() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'instr'
     */
    public static int sizeBits_instr() {
        return 8;
    }

}
