COMPONENT=GreenHouseC

CFLAGS += -I$(TOSDIR)/lib/net
CFLAGS += -I$(TOSDIR)/lib/net/ctp
CFLAGS += -I$(TOSDIR)/lib/diagmsg
CFLAGS += -I$(TOSDIR)/lib/net/4bitle
CFLAGS += -DTOSH_DATA_LENGTH=100

include $(MAKERULES)
