/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DataMsg'
 * message type.
 */

public class DataMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 28;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new DataMsg of size 28. */
    public DataMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DataMsg of the given data_length. */
    public DataMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg with the given data_length
     * and base offset.
     */
    public DataMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg using the given byte array
     * as backing store.
     */
    public DataMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public DataMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DataMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg embedded in the given message
     * at the given base offset.
     */
    public DataMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg embedded in the given message
     * at the given base offset and length.
     */
    public DataMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DataMsg> \n";
      try {
        s += "  [cmd=";
        for (int i = 0; i < 26; i++) {
          s += "0x"+Long.toHexString(getElement_cmd(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [length=0x"+Long.toHexString(get_length())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: cmd
    //   Field type: short[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'cmd' is signed (false).
     */
    public static boolean isSigned_cmd() {
        return false;
    }

    /**
     * Return whether the field 'cmd' is an array (true).
     */
    public static boolean isArray_cmd() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'cmd'
     */
    public static int offset_cmd(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 26) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'cmd'
     */
    public static int offsetBits_cmd(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 26) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'cmd' as a short[]
     */
    public short[] get_cmd() {
        short[] tmp = new short[26];
        for (int index0 = 0; index0 < numElements_cmd(0); index0++) {
            tmp[index0] = getElement_cmd(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'cmd' from the given short[]
     */
    public void set_cmd(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_cmd(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'cmd'
     */
    public short getElement_cmd(int index1) {
        return (short)getUIntBEElement(offsetBits_cmd(index1), 8);
    }

    /**
     * Set an element of the array 'cmd'
     */
    public void setElement_cmd(int index1, short value) {
        setUIntBEElement(offsetBits_cmd(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'cmd'
     */
    public static int totalSize_cmd() {
        return (208 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'cmd'
     */
    public static int totalSizeBits_cmd() {
        return 208;
    }

    /**
     * Return the size, in bytes, of each element of the array 'cmd'
     */
    public static int elementSize_cmd() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'cmd'
     */
    public static int elementSizeBits_cmd() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'cmd'
     */
    public static int numDimensions_cmd() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'cmd'
     */
    public static int numElements_cmd() {
        return 26;
    }

    /**
     * Return the number of elements in the array 'cmd'
     * for the given dimension.
     */
    public static int numElements_cmd(int dimension) {
      int array_dims[] = { 26,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'cmd' with a String
     */
    public void setString_cmd(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_cmd(i, (short)s.charAt(i));
         }
         setElement_cmd(i, (short)0); //null terminate
    }

    /**
     * Read the array 'cmd' as a String
     */
    public String getString_cmd() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,26)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_cmd(i) == (char)0) break;
             carr[i] = (char)getElement_cmd(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: length
    //   Field type: int, unsigned
    //   Offset (bits): 208
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'length' is signed (false).
     */
    public static boolean isSigned_length() {
        return false;
    }

    /**
     * Return whether the field 'length' is an array (false).
     */
    public static boolean isArray_length() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'length'
     */
    public static int offset_length() {
        return (208 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'length'
     */
    public static int offsetBits_length() {
        return 208;
    }

    /**
     * Return the value (as a int) of the field 'length'
     */
    public int get_length() {
        return (int)getUIntBEElement(offsetBits_length(), 16);
    }

    /**
     * Set the value of the field 'length'
     */
    public void set_length(int value) {
        setUIntBEElement(offsetBits_length(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'length'
     */
    public static int size_length() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'length'
     */
    public static int sizeBits_length() {
        return 16;
    }

}
