COMPONENT=ApplicationC
SENSORBOARD=mts400
CFLAGS += -I$(SZTETOSDIR)/sensorboards/mts400
CFLAGS += -I$(SZTETOSDIR)/lib/StreamStorage
CFLAGS += -I$(SZTETOSDIR)/lib/StorageFrame
CFLAGS += -I$(SZTETOSDIR)/lib/Dfrf
CFLAGS += -I$(SZTETOSDIR)/lib/StreamUploaderDfrf
CFLAGS += -I$(SZTETOSDIR)/lib/TimeSyncPoints

include $(MAKERULES)